services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    volumes:
      - ./client/src:/app/src
      - ./client/public:/app/public
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - PORT=3000

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    volumes:
      - ./server:/app
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development
      - PORT=3001

networks:
  default:
    driver: bridge